package cz.muni.fi.car.leasing.gui;

import cz.muni.fi.car.leasing.Car;
import cz.muni.fi.car.leasing.CarManager;
import cz.muni.fi.car.leasing.CarManagerImpl;
import cz.muni.fi.car.leasing.Customer;
import cz.muni.fi.car.leasing.CustomerManager;
import cz.muni.fi.car.leasing.CustomerManagerImpl;
import cz.muni.fi.car.leasing.Lease;
import java.awt.Window;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.sql.DataSource;
import javax.swing.AbstractListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;

/**
 * This file contains 1 jpanel class and 2 abstractListModel classes
 * @author Jackie
 */
public class LeasePopUp extends javax.swing.JPanel {

    private String action;
    private Lease lease;
    private ResourceBundle texts;
    private JTable table;
    private CustomerListModel customersModel = new CustomerListModel();
    private CarListModel carsModel = new CarListModel();
    
    /**
     * Creates new form LeasePopUp
     */
    public LeasePopUp(String action,Lease lease,
            ResourceBundle texts,JTable leaseTable,DataSource dataSource) {
        initComponents();
        this.action = action;
        this.lease = lease;
        this.texts = texts;
        this.table = leaseTable;
        CustomerManager customerManager = new CustomerManagerImpl(dataSource);
        CarManager carManager = new CarManagerImpl(dataSource);
        jList1.setModel(customersModel);
        jList2.setModel(carsModel);  
        customersModel.addCustomer(null);
        carsModel.addCar(null);
        //examples
        customersModel.addListOfCustomers(customerManager.findAll());
        carsModel.addListOfCars(carManager.findAll());
        
        switch(action){
            case "add":
                jLabel1.setText(texts.getString("addLease"));
                break;
            case "edit":
                jLabel1.setText(texts.getString("editLease"));
                setTextsFromLease(lease);
                setSelectedCarAndCustomer(lease.getCustomerId(),lease.getCarId());
                break;
            case "filter":
                jLabel1.setText(texts.getString("filterLeases"));
                setTextsFromLease(lease);
                setSelectedCarAndCustomer(lease.getCustomerId(),lease.getCarId());
                break;
        }
        
    }
    
    private void setTextsFromLease(Lease l){
        //all values dont have to be setted cause filterCustomer can have all field null
        if(l.getStartTime() != null)
            jTextField1.setText(l.getStartTime().toString());
        if(l.getExpectedEndTime() != null)
            jTextField2.setText(l.getExpectedEndTime().toString());
        if(l.getRealEndTime() != null) 
            jTextField3.setText(l.getRealEndTime().toString());
        if(l.getPrice() != null)
            jTextField4.setText(l.getPrice().toString());
        if(l.getFee() != null)
            jTextField5.setText(l.getFee().toString());        
    }

    private void setSelectedCarAndCustomer(Long cusId,Long carId){
        if(cusId != null){
            jList1.setSelectedIndex(customersModel.getIndexOfCustomerWithId(cusId));
        }
        if(carId != null){
            jList2.setSelectedIndex(carsModel.getIndexOfCarWithId(carId));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("texts"); // NOI18N
        jLabel2.setText(bundle.getString("customer")); // NOI18N

        jLabel3.setText(bundle.getString("car")); // NOI18N

        jLabel4.setText(bundle.getString("start")); // NOI18N

        jTextField1.setToolTipText(bundle.getString("tooltipStart")); // NOI18N

        jLabel5.setText(bundle.getString("end")); // NOI18N

        jTextField2.setToolTipText(bundle.getString("tooltipStart")); // NOI18N

        jLabel6.setText(bundle.getString("realEnd")); // NOI18N

        jTextField3.setToolTipText(bundle.getString("tooltipStart")); // NOI18N

        jLabel7.setText(bundle.getString("price")); // NOI18N

        jLabel8.setText(bundle.getString("fee")); // NOI18N

        jButton1.setText(bundle.getString("ok")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(bundle.getString("cancel")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                            .addComponent(jTextField2)
                                            .addComponent(jTextField3)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                                .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 188, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switch(action){
            case "add":
                addNewLease();
                break;
            case "edit":
                editLease();
                break;
            case "filter":
                filterLease();
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Window win = SwingUtilities.getWindowAncestor(this);
        win.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    private void addNewLease() {
        Lease newLease = new Lease();
        List<String> errors = checkCorrectnessOfTextInput();
        if(!errors.isEmpty()){
            JOptionPane.showMessageDialog(null,
                    texts.getString("fillUpAllFields") +": "+
                            errors.toString(),texts.getString("fillUpAllFields"),
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        fillLeaseFromTextInput(newLease);
        
        ((LeaseTableModel)table.getModel()).addLease(newLease);
        Window win = SwingUtilities.getWindowAncestor(this);
        win.dispose();
    }
    
    private void fillLeaseFromTextInput(Lease lease){
        Customer cus = customersModel.getSelectedCustomer(jList1.getSelectedIndex());
        if(cus != null){
            lease.setCustomerId(cus.getId());
        }
        Car car = carsModel.getSelectedCar(jList2.getSelectedIndex());
        if(car != null){
            lease.setCarId(car.getId());
        }
        lease.setStartTime(LocalDateTime.parse(jTextField1.getText().trim()));
        lease.setExpectedEndTime(LocalDateTime.parse(jTextField2.getText().trim()));
        if(jTextField3.getText().trim().isEmpty()){
            lease.setRealEndTime(null);
        }else{
            lease.setRealEndTime(LocalDateTime.parse(jTextField3.getText().trim()));
        }
        lease.setPrice(new BigDecimal(jTextField4.getText().trim()));
        
        if(jTextField5.getText().trim().isEmpty()){
            lease.setFee(null);
        }else{
            lease.setFee(new BigDecimal(jTextField5.getText().trim()));
        }
        
    }

    private void editLease() {
        List<String> errors = checkCorrectnessOfTextInput();
        if(!errors.isEmpty()){
            JOptionPane.showMessageDialog(null,
                    texts.getString("fillUpAllFields") +": "+
                            errors.toString(),texts.getString("fillUpAllFields"),
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        fillLeaseFromTextInput(lease);
        int selectedRow = table.getSelectedRow();
        ((LeaseTableModel)table.getModel()).updateLease(lease, selectedRow);
        
        Window win = SwingUtilities.getWindowAncestor(this);
        win.dispose();
    }

    private void filterLease() {
        List<String> errors = checkCorrectnessOfTextInputForFiltering();
        if(!errors.isEmpty()){
            JOptionPane.showMessageDialog(null,
                    texts.getString("fillUpAllFields") +": "+
                            errors.toString(),texts.getString("fillUpAllFields"),
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        fillUpLeaseForFilterFromTextInput();
        
        ((LeaseTableModel)table.getModel()).filterLeases();
        table.updateUI();
        
        Window win = SwingUtilities.getWindowAncestor(this);
        win.dispose();
        
    }

    private List<String> checkCorrectnessOfTextInput() {
        List<String> errors = new ArrayList<>();
        if(jList1.getSelectedIndex()==-1 || jList1.getSelectedIndex()==0){
            errors.add(jLabel2.getText());
        }
        if(jList2.getSelectedIndex()==-1 || jList2.getSelectedIndex()==0){
            errors.add(jLabel3.getText());
        }
        if(!isDateTimeFormatCorrect(jTextField1.getText().trim())){
            errors.add(jLabel4.getText());
        }
        if(!isDateTimeFormatCorrect(jTextField2.getText().trim())){
            errors.add(jLabel5.getText());
        }
        if(!jTextField3.getText().trim().isEmpty()){
            if(!isDateTimeFormatCorrect(jTextField3.getText().trim())) {
                errors.add(jLabel6.getText());
            }
        }
        if(!jTextField4.getText().trim().matches("\\d+")){
            errors.add(jLabel7.getText());
        }
        if(!jTextField5.getText().trim().isEmpty()){
            if(!jTextField5.getText().trim().matches("\\d+")){
                errors.add(jLabel8.getText());
            }
        }
        
        return errors;
    }
    private boolean isDateTimeFormatCorrect(String dateTime){
        if(!dateTime.matches("\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}")){
            return false;
        }
        try {
            LocalDateTime.parse(dateTime);
        } catch (DateTimeParseException ex) {
            return false;
        }
        return true;
    }    
    
    private List<String> checkCorrectnessOfTextInputForFiltering(){
        List<String> errors = new ArrayList<>();
        if(!jTextField1.getText().trim().isEmpty() && !isDateTimeFormatCorrect(jTextField1.getText().trim()))
            errors.add(jLabel4.getText());
        if(!jTextField2.getText().trim().isEmpty() && !isDateTimeFormatCorrect(jTextField2.getText().trim()))
            errors.add(jLabel5.getText());
        if(!jTextField3.getText().trim().isEmpty() && !isDateTimeFormatCorrect(jTextField3.getText().trim()))
            errors.add(jLabel6.getText());
        if(!jTextField4.getText().trim().isEmpty() && !jTextField4.getText().trim().matches("\\d+"))
            errors.add(jLabel7.getText());
        if(!jTextField5.getText().trim().isEmpty() && !jTextField5.getText().trim().matches("\\d+"))
            errors.add(jLabel8.getText());
        return errors;            
    }
        
    private void fillUpLeaseForFilterFromTextInput(){
        //customerId
        if(jList1.getSelectedIndex() > 0) {
            Customer cus = customersModel.getSelectedCustomer(jList1.getSelectedIndex());
            if(cus != null) {
                lease.setCustomerId(cus.getId());
            } else {
                lease.setCustomerId(null);
            }
        }
        //carId
        if(jList2.getSelectedIndex() > 0) {
            Car car = carsModel.getSelectedCar(jList2.getSelectedIndex());
            if(car != null) {
                lease.setCarId(car.getId());
            } else {
                lease.setCarId(null);
            }
        }
        //startTime
        if(!jTextField1.getText().trim().isEmpty() && isDateTimeFormatCorrect(jTextField1.getText().trim()))
            lease.setStartTime(LocalDateTime.parse(jTextField1.getText().trim()));
        else
            lease.setStartTime(null);
        //expectedEndTime
        if(!jTextField2.getText().trim().isEmpty() && isDateTimeFormatCorrect(jTextField2.getText().trim()))
            lease.setExpectedEndTime(LocalDateTime.parse(jTextField2.getText().trim()));
        else
            lease.setExpectedEndTime(null);
        //realEndTime
        if(!jTextField3.getText().trim().isEmpty() &&isDateTimeFormatCorrect(jTextField3.getText().trim()))
            lease.setRealEndTime(LocalDateTime.parse(jTextField3.getText().trim()));
        else
            lease.setRealEndTime(null);
        //price
        if(!jTextField4.getText().trim().isEmpty() && jTextField4.getText().trim().matches("\\d+"))
            lease.setPrice(new BigDecimal(jTextField4.getText().trim()));
        else
            lease.setPrice(null);
        //fee
        if(!jTextField5.getText().trim().isEmpty() && jTextField5.getText().trim().matches("\\d+"))
            lease.setFee(new BigDecimal(jTextField5.getText().trim()));
        else
            lease.setFee(null);
        
    }
    

}

class CarListModel extends AbstractListModel{

    private final List<Car> cars = new ArrayList<>();
    
    @Override
    public int getSize() {
        return cars.size();
    }

    @Override
    public Object getElementAt(int index) {
        if(index > getSize()-1) 
            return null;
        return cars.get(index);
    }
    
    public void addCar(Car car){
        cars.add(car);        
        fireIntervalAdded(this, getSize()-1, getSize()-1);
    }
    
    public void addListOfCars(List<Car> list){
        int before = getSize();
        cars.addAll(list);
        fireIntervalAdded(this, before, getSize());
    }
    
    public Car getSelectedCar(int index){
        if(index > getSize()-1) 
            return null;
        return cars.get(index);
    }
    
    public int getIndexOfCar(Car car){
        return cars.indexOf(car);
    }
    
    public int getIndexOfCarWithId(Long id){
        int index=0;
        for(Car c: cars){
            if(c != null) {
                if(id.equals(c.getId())) {
                    return index;
                }
            }
            index++;
        }
        return 0;
    }
    
}

class CustomerListModel extends AbstractListModel{
    
    private final List<Customer> customers = new ArrayList<>();

    @Override
    public int getSize() {
        return customers.size();
    }

    @Override
    public Object getElementAt(int index) {
        if(index >= getSize() || index<0) 
            return null;
        return customers.get(index);
    }
    
    public void addCustomer(Customer customer){
        customers.add(customer);
        fireIntervalAdded(this, getSize()-1, getSize()-1);
    }
    
    public void addListOfCustomers(List<Customer> list){
        int before = getSize();
        customers.addAll(list);
        fireIntervalAdded(this, before, getSize());
    }
    
    public Customer getSelectedCustomer(int index) {
        if(index >= getSize() || index<0) 
            return null;
        return customers.get(index);
    }
    
    public int getIndexOfCustomer(Customer customer){
        return customers.indexOf(customer);
    }
    
    public int getIndexOfCustomerWithId(Long id){
        int index=0;
        for(Customer c: customers){
            if(c != null) {
                if(id.equals(c.getId())) {
                    return index;
                }
            }
            index++;
        }
        return 0;
    }
}